# -*- coding: utf-8 -*-
"""corpus_Work_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gJOxnAb3rIMA9r51U64qAFZZ4xN39nEd
"""

import nltk

# -*- coding: UTF-8 -*-


from collections import Counter
#nltk.download('gutenberg')
text = nltk.corpus.gutenberg.raw('chesterton-thursday.txt')

#nltk.download('punkt')
tokenized_sents=nltk.sent_tokenize(text)
print(len(tokenized_sents))

#print(tokenized_sents)
tokenized_word=nltk.word_tokenize(text)

print(len(tokenized_word))
print(len(tokenized_sents)/len(tokenized_word))

labeled_docs = [(doc, 'chesterton-thursday') for doc in tokenized_sents]

print(labeled_docs)

doc = ""
labeled_docs=[]
for i, sent in enumerate(tokenized_sents):
	doc += sent
	if i%5==0:
		labeled_docs.append( [(doc, 'chesterton-thursday') ])
		doc = ""
		
print(labeled_docs)